### ISSUE TITLE
API Meeting notes

### ISSUE THREAD

**Issue by Pratyush** [arkworks-rs/sponge#9]
From meeting:
- sponge outputs should be n bits, n bytes, and n field elements
- make a SpongeParams trait which has a few parameters:
	- BLOCK_SIZE_IN_BITS
	- BLOCK_SIZE_IN_FE
	- ComputationType: enum { Binary, Algebraic}
- absorbable should take as input `params: SpongeParams`, and then make decisions on how to serialize itself to optimize for better efficiency with the sponge (mostly useful for curve point serialization)
```rust
trait Absorbable {
	fn to_bytes_with_params(_params: SpongeParams) {
		Self::to_bytes()
	}
	
	fn to_bytes();
	
	// similar for field elements
}
```

TODO: Find better name for `Sponge` trait

**Comment by Will-Lin4** [comment]
Did we still want to implement domain separation in the sponge?

**Comment by weikengchen** [comment]
I think we should!

**Comment by ValarDragon** [comment]
We forgot to add domain separation when writing the issue 😅. I think the conclusion was to make the Sponge's `new` fn take in an `Option<&str>` or `Option<&[u8]>`

**Comment by tsunrise** [comment]
I think we can close this issue now
